### ISSUE TITLE
How can I set js_errors to false ?

### ISSUE THREAD

**Issue by changwuf31** [jcalderonzumba/gastonjs#11]
Anyway, great library :+1:

**Comment by jcalderonzumba** [comment]
Hey @changwuf31 sorry for the late reply, I got no notifications for this issue. I have worked with documentation, i think the answer is here:

http://gastonjs.readthedocs.org/en/latest/api/commands/javascript/set_js_errors/

Let me know if this helps so i can close the issue.

**Comment by changwuf31** [comment]
Arr.. thank u, but i'm using it with the php driver.. Guess I should open the issue there ?

**Comment by jcalderonzumba** [comment]
Yeah, open it there.

**Comment by bamarni** [comment]
@jcalderonzumba what about being able to preconfigure this on phantomjs boot script? See https://github.com/jcalderonzumba/gastonjs/pull/17
